version: 2
updates:
  # Astro Framework Ecosystem - Weekly updates, grouped to prevent conflicts
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
      timezone: 'America/Chicago'
    groups:
      astro-ecosystem:
        patterns:
          - 'astro'
          - '@astrojs/*'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(dev-deps)'
      include: 'scope'
    open-pull-requests-limit: 3
    reviewers:
      - 'danhendersonede'
    labels:
      - 'dependencies'
      - 'astro'

  # React Ecosystem - Weekly updates, grouped for compatibility
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
      timezone: 'America/Chicago'
    groups:
      react-ecosystem:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'motion'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(dev-deps)'
      include: 'scope'
    open-pull-requests-limit: 2
    reviewers:
      - 'danhendersonede'
    labels:
      - 'dependencies'
      - 'react'

  # Development Tooling - Daily updates for linting/formatting (works with husky)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Chicago'
    groups:
      dev-tooling:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - 'prettier*'
          - 'husky'
          - 'lint-staged'
          - 'typescript'
    commit-message:
      prefix: 'chore(dev-deps)'
      include: 'scope'
    open-pull-requests-limit: 5
    reviewers:
      - 'danhendersonede'
    labels:
      - 'dependencies'
      - 'tooling'
    # Auto-merge patch updates for dev tooling since husky will catch issues
    allow:
      - dependency-type: 'development'
        update-type: 'version-update:semver-patch'

  # Security Updates - Immediate updates with auto-merge for patches
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'America/Chicago'
    commit-message:
      prefix: 'fix(security)'
      include: 'scope'
    open-pull-requests-limit: 10
    reviewers:
      - 'danhendersonede'
    labels:
      - 'dependencies'
      - 'security'
      - 'priority-high'
    # Auto-merge security patches since pre-commit hooks will validate
    allow:
      - dependency-type: 'all'
        update-type: 'security-update'

  # Monthly comprehensive update check for remaining packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'first-tuesday'
      time: '09:00'
      timezone: 'America/Chicago'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(dev-deps)'
      include: 'scope'
    open-pull-requests-limit: 3
    reviewers:
      - 'danhendersonede'
    labels:
      - 'dependencies'
      - 'monthly-review'
    ignore:
      # Ignore packages already handled by other update configs
      - dependency-name: 'astro'
      - dependency-name: '@astrojs/*'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react*'
      - dependency-name: 'motion'
      - dependency-name: 'eslint*'
      - dependency-name: '@eslint/*'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: 'prettier*'
      - dependency-name: 'husky'
      - dependency-name: 'lint-staged'
      - dependency-name: 'typescript'
