[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]
	package = "@netlify/plugin-lighthouse"

	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 1.0
		best-practices = 1.0
		seo = 1.0

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"

[[plugins]]
	package = "@netlify/plugin-a11y"

	[plugins.inputs]
		wcagLevel = "WCAG2AAA"

[[plugins]]
	package = "@netlify/plugin-sitemap"

[[plugins]]
	package = "netlify-plugin-no-more-404"