[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]
	package = "@netlify/plugin-lighthouse"

	[plugins.inputs.thresholds]
		performance = 0.9
		accessibility = 1.0
		best-practices = 0.9
		seo = 0.9

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"

[[plugins]]
	package = "@netlify/plugin-a11y"

	[plugins.inputs]
		wcagLevel = "WCAG2AAA"
		ignoreElements = ['iframe', '#articles > ul > li a']

[[plugins]]
	package = "@netlify/plugin-sitemap"

# [[plugins]]
	# package = "netlify-plugin-no-more-404"

[[redirects]]
  # Uses Netlify Image CDN
  from = "/img/full/:file"
  to = "/.netlify/images?url=/images/:file"
  status = 200

[[redirects]]
	# Grab particular sizes from the Image CDN
  from = "/img/:width/:file"
  to = "/.netlify/images?url=/images/:file&width=:width"
  status = 200
